name: CI
on: push

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: pwd
      - run: echo "test"
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: tests
        run: poetry run pytest