name: CI
on: push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: tests
        run: poetry run pytest

      
  deploy:
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    needs: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: build
        run: poetry build
      - name: publish
        run: poetry publish -u thibaultB -p ${{ secrets.PYPI_PASSWORD }}